config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :students, controllers: {
      sessions: 'students/sessions',
      registrations: 'students/registrations',
      schedules: 'students/schedules',
      scheduled_students: 'students/scheduled_students'
  }
  devise_for :teachers, controllers: {
      sessions: 'teachers/sessions',
      registrations: 'teachers/registrations'
  }
  devise_scope :students do
    get 'students/sign_in', to:'students/sessions#new', as: :students_sign_in
    get 'students/sign_up', to:'students/registrations#new', as: :students_sign_up
    delete 'students/sign_out', to: 'students/sessions#destroy', as: :students_sign_out
    get 'students/forgot_password', to:'students/passwords#new', as: :students_forgot_password
    get 'students/reset_password', to:'students/password#edit', as: :students_reset_password
    get 'students/schedule', to:'pages#student_schedule', as: :students_schedule
    get 'students/new_schedule', to: 'students/scheduled_students#new', as: :new_scheduled_students
    post 'students/scheduled_student', to: 'students/scheduled_students#create', as: :create_scheduled_students
    delete 'students/scheduled_student', to: 'students/scheduled_students#destroy', as: :delete_scheduled_students
    get 'students/schedule/renew', to: 'students/schedules#renew', as: :renew_students_schedule
  end
  devise_scope :teachers do
    get 'teachers/sign_in', to:'teachers/sessions#new', as: :teachers_sign_in
    get 'teachers/sign_up', to:'teachers/registrations#new', as: :teachers_sign_up
    get 'teachers/forgot_password', to:'teachers/passwords#new', as: :teachers_forgot_password
    get 'teachers/reset_password', to:'teachers/password#edit', as: :teachers_reset_password
    get 'teachers/locations', to:'pages#teacher_locations', as: :teachers_locations
    get 'teachers/schedules', to:'pages#teacher_schedules', as: :teachers_schedules
    delete 'teachers/sign_out', to: 'teachers/sessions#destroy', as: :teachers_sign_out
  end
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  resources :locations, only: [:create, :destroy]

end

app/views/pages/_location_form.html.erb
<style>
  .field{width: 18%;margin: 0 ; padding: 0}

</style>
<%= form_for(@location) do |form| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% @location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <table class="newLocation">
    <thead>
    <th class="filed">New Location</th>
    <th class="field">
      <%= form.label :place %>
      <%= form.select :place, Location.places.keys.map {|r| [r.humanize, r]}%>
    </th>
    <th class="field">
      <%= form.label :weekday %>
      <%= form.select :weekday, Location.weekdays.keys.map {|r| [r.humanize, r]} %>
    </th>
    <th class="field">
      <%= form.label :start_time, "Start time" %>
      <%= form.time_select :start_time, {minute_step: 30, start_hour: 7, end_hour: 21} %>
    </th>
    <!--  <div class="field">-->
    <%#= form.label :end_time, "Finish time" %>
    <%#= form.hidden_field :end_time, calc_end_time(start_time) %>
    <!--  </div>-->
    <th class="actions">
      <%= form.submit "New location" %>
    </th>
    </thead>

  </table>

<% end %>

app/views/pages/student_schedule.html.erb
<style type="text/css">
  .text{width: 50%;}
  .start-time{width: 50%;color: #B00100;font-size: 150%}
  div{display: inline}
</style>
<!--逻辑麻烦，修改界面请认真阅读，特别是不要缺少<%#end%>-->
<section class=" mt-7" id="help">
  <div class="container">
    <div class="row">
      <div class="col-md-10 mx-auto">
        <h2 class="dot-circle">Schedule Infomation</h2>
        <p class="text-muted lead">Please check your schedule infomation</p>
        <% if current_student.scheduled_student %>
          <% scheduled_student = current_student.scheduled_student %>


          <% if scheduled_student.schedules.active.any? %>
            <% s = scheduled_student.schedules.active[0] %>
            <% l = s.location %>
          <div class="row mt-5 card-contacts">

          <div class="col-md-6 mb-3">
            <div class="card">
              <div class="card-body text-center">
                <div class="icon-box">
                  <div class="icon-box-inner small-xs text-primary">
                    <span data-feather="inbox" width="30" height="30"></span>
                  </div>
                </div>

                  <h5>Basic Infomation</h5>
                <div class="start-time"><%= "#{l.place}" %>  </div>&nbsp;
                <div class="start-time"><%= "#{l.teacher.name}" %></div>&nbsp;

                  <div class="start-time"><u><%= "#{s.scheduled_times}" %></u></div>
                  <div class="text"> times</div>

              </div>

            </div>
          </div>

          <div class="col-md-6 mb-3">
            <div class="card">
              <div class="card-body text-center">
                <div class="icon-box">
                  <div class="icon-box-inner small-xs text-primary">
                    <span data-feather="message-circle" width="30" height="30"></span>
                  </div>
                </div>

                <h5>Time Infomation</h5>
                <% if Time.now < s.next_start_time %>

                  <div class="start-time"><%= "#{l.weekday}" %></div>
                  <div class="start-time"><%= "#{s.next_start_time}"%>  </div>
                <% else %>
                  <div class="start-time">The original time is out,Please Renew Schedule </div>
                <% end %>
              </div>
            </div>
          </div>

            <% elsif scheduled_student.schedules.pending.any? %>
             <% pending_schedules = scheduled_student.schedules.pending %>
             <% pending_schedules.each do |s|%>
             <% l = s.location %>
            <%= "There are #{check_pending_num(l)} people in front of your schedule at #{l.place}, #{l.weekday}, #{l.start_time.to_s(:hm)}, teacher #{s.teacher.name}" %>
            <% end %>
            </div>
            <% end %>
          <% else %>
        <% end %>

        <div class="row mt-5">
          <div class="col-md-6 mb-5" style="text-align: center">
            <h6>Do you want to cancel your schedule?</h6>
            <%= link_to "Destroy schedule!", delete_scheduled_students_path, method: "delete" ,class:"btn btn-primary"%>
          </div>
          <% if current_student.scheduled_student %>
            <% scheduled_student = current_student.scheduled_student %>


            <% if scheduled_student.schedules.active.any? %>
              <% s = scheduled_student.schedules.active[0] %>
              <% if Time.now < s.next_start_time %>
            <div class="col-md-6 mb-5" style="text-align: center">
              <h6>Creat a new schedule!</h6>
              <%= link_to 'New schedule!', new_scheduled_students_path,class:"btn btn-primary"%>
            </div>
              <% else %>
                <div class="col-md-6 mb-5" style="text-align: center">
                  <h6>Renew a schedule!</h6>
                  <%= link_to 'Renew schedule!', renew_students_schedule_path,class:"btn btn-primary"%>

                </div>
              <% end %>
            <% end %>
          <% else %>
            <div class="col-md-6 mb-5" style="text-align: center">
              <h6>Creat a new schedule!</h6>
              <%= link_to 'New schedule!', new_scheduled_students_path,class:"btn btn-primary"%>
            </div>
          <% end %>
          <div class="col-md-6 mb-5">
            <h6>Destory</h6>
            <p class="text-muted">Cancellation of appointment means that consultation will be abandoned</p>
          </div>

          <div class="col-md-6 mb-5">
            <h6>Creat</h6>
            <p class="text-muted">Create a new appointment, you can choose the time and place of your own teacher</p>
        </div>
          <div class="col-md-6 mb-5">
            <h6>Reschedule after cancellation</h6>
            <p class="text-muted">After canceling you can click new to make an appointment again</p>
          </div>
          <div class="col-md-6 mb-5">
            <h6>Renew after creation</h6>
            <p class="text-muted">When the last appointment timed out, you can click Renew to renew</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/teacher_locations.html.erb
<style type="text/css">
  h3{text-align: center}
  /*td{text-align: center;padding: 20px}*/
  /*th{text-align: center;padding: 20px}*/
  table{width: 90%; margin: 0 5%; text-align: center}
  th,td{width: 18%;margin: 0 ; padding: 0}
</style>

<h3>Locations</h3>
<br/>
<% if current_teacher.locations.any? %>
  <table>
    <thead>
    <tr>
      <th >Place</th>
      <th >Start Time</th>
      <th >Finish Time</th>
      <th >Weekday</th>
      <th ></th>
    </tr>
    </thead>

    <tbody>
    <% current_teacher.locations[0..-2].each do |l| %>
      <tr class="locations">
        <td ><%= l.place %></td>
        <td ><%= l.start_time.to_formatted_s(format = :hm) %></td>
        <td ><%= l.end_time.to_formatted_s(format = :hm) %></td>
        <td ><%= l.weekday %></td>
        <td ><%= link_to 'Destroy', l, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        <td></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br/>
<% end %>
<br/>
<hr style="width:100%;">
<section class="location_form">
  <%= render 'pages/location_form' %>
</section>

app/views/pages/teacher_schedules.html.erb
<style type="text/css">
  h2{text-align: center}
  h4{text-align: center}
  /*td{text-align: center;padding: 20px}*/
  /*th{text-align: center;padding: 20px}*/
  table{width: 90%; margin: 0 5%; text-align: center}
  th,td{width: 18%;margin: 0 ; padding: 0}
</style>
<h2>Your schedules</h2>
<br/>
<table>
  <thead>
  <tr>
    <th >Student Name</th>
    <th >Date</th>
    <th >Start Time</th>
    <th >Place</th>
  </tr>
  </thead>
  <tbody>
  <% @schedules.each do |schedule| %>
  <tr>
    <td ><%= schedule.student.name %></td>
    <td ><%= schedule.next_start_time.strftime("%Y-%m-%d") %></td>
    <td ><%= schedule.next_start_time.to_s(:hm) %></td>
    <td ><%= schedule.location.place %></td>
  </tr>
  <% end %>
  </tbody>
</table>
<hr style="width:100%;">
<br/>
<h4>Over timed schedules (not renew yet)</h4>
<br/>
<table>
  <thead>
  <tr>
    <th>Student Name</th>
    <th>Date</th>
    <th>Start Time</th>
    <th>Place</th>
  </tr>
  </thead>
  <tbody>
  <% @over_time_schedules.each do |schedule| %>
    <tr>
      <td><%= schedule.student.name %></td>
      <td><%= schedule.next_start_time.strftime("%Y-%m-%d") %></td>
      <td><%= schedule.next_start_time.to_s(:hm) %></td>
      <td><%= schedule.location.place %></td>
<!--     TODO: -->
      <td><%= link_to "Destroy", '#' %></td>
    </tr>
  <% end %>
  </tbody>
</table>